# .env file to load
# if file not found logs warning
dotenv: .env
# host to bind to
host: 0.0.0.0
# port to listen to
port: 80
# env variable to get the do auth token from
doAuthTokenEnv: DO_AUTH_TOKEN
# TTL for domain entries
ttl: 60
# File to load for ddns data
ddns_file: /etc/ddns_do/ddns

# Default prioritization for sent or remote ip (sent, remote, error)
# what ip to use when the sent and remote ip dont match
default_prioritize: sent

# Url or Path for suffix_list
# If a url, it downloads the list on startup
suffixList: https://publicsuffix.org/list/public_suffix_list.dat
# suffixList: /etc/ddns_do/suffix.dat

# HTTP query parameter mapping
query:
  ip: ip
  domain: domain
  user: user
  password: password
  prioritize: prioritize