name: ddns_do
description: A sample command-line application.
version: ${version}
homepage: https://github.com/TheKingDave/ddns_do

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  args: ^1.6.0
  dotenv: ^2.0.0
  http: ^0.12.1
  public_suffix: ^1.2.1
  yaml: ^2.2.1
  dbcrypt: ^1.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
